apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
spec:
  selector:
    matchLabels:
      name: log-agent
  template:
    metadata:
      labels:
        name: log-agent
    spec:
      containers:
      - name: log-agent
        image: alpine:3.15
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache curl
          echo "Log agent started on node $(hostname)"
          mkdir -p /collected-logs
          while true; do
            curl -s http://app-service/logs > /collected-logs/app_$(date +%s).log
            echo "$(date): Collected logs from application"
            cat /collected-logs/app_*.log | sort | tail -10
            sleep 30
          done
        volumeMounts:
        - name: collected-logs
          mountPath: /collected-logs
      volumes:
      - name: collected-logs
        emptyDir: {}
