apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: custom-app
  endpoints:
  - port: 8080
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default